# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-07 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='picture',
            field=models.TextField(blank=True, null=True),
        ),
    ]
